language: rust
rust: stable
cache: cargo

before_install:
  - chmod 755 ./install-rojo.sh

install:
  - ./install-rojo.sh

script:
  - echo "TODO, run tests"

after_success:
#  - rojo upload --cookie "$ROBLOSECURITY" --place_id 2751232980
  - ./upload-place.sh
  - echo "Build successful"