language: rust
rust: stable
cache: cargo

before_install:
  - chmod 755 ./install-rojo.sh
  - chmod 755 ./upload-place.sh

install:
  - ./install-rojo.sh

script:
  - echo "TODO, run tests"
  - echo "$TRAVIS_BRANCH"

after_success:
  - ./upload-place.sh
  - echo "Build successful"